[package]
name = "simple-qc"
version = "0.1.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
flate2 = "1.0.19"
glob = "0.3.0"
rayon = "1.5.0"
num-format = "0.4.0"

[profile.release]
lto = true
